apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::296062577418:role/eksctl-demo-cluster-1-cluster-ServiceRole-gjVqebBuHKEx
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::296062577418:role/service-role/codebuild-webapp-project-dev-service-role
      username: build
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::296062577418:user/sushant
      username: sushant
      groups:
        - system:masters



